### ISSUE TITLE
Character sheet show blank page (Rolisteam 1.9)

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/RCharacterSheet#4]
#Your configuration:
Rolisteam version: 
Operating System and version :  Windows 10

Rolisteam Setting (remove irrelevant):  
* GM and Server (localhost)
* Client 

#What did you do ? (Explain each step from starting rolisteam to the issue)
- Loaded a previously saved .rcs file
- shared a sheet with my client 

#What did you expect to see ? 
- The characters sheets as they are displayed in 1.8.2

#What did you get instead ? (Describe in details the issue) 
- A blank page on both GM and Server AND and on client only

I tried on many files even some I shared on GitHub, same result
And if I regenerate the code from RCSE, i lost background images...

Is there something to do to upgrade character sheet from 1.8.2 to 1.9 ?

**Comment by sioc-de-narf** [comment]
hum... 

Are you sure it is **_color_** => **_backgroundColor_** ?

When i look at the code of a 1.8 sheet i see : **_bgcolor_** and no just **_color_**

**Comment by obiwankennedy** [comment]
It is property from the rolisteam sdk. So those files: https://github.com/Rolisteam/RCharacterSheet/tree/master/qml/Rolisteam. Those with v1 at the end of the name are from Rolisteam v1.8.

Many of them have textColor property to define the color of the text and color to define background color.
In v1.9, I decide to clean up the API, so textColor is not color, and color is not backgroundColor.
As an example, you can compare the code of  TextInputFieldv1.qml and  TextInputFieldv1.qml.

**Comment by sioc-de-narf** [comment]
Ok, so i tried :

- Minimal update => worked.

- Complete Update =>  didn't worked => white page 

- The Script : Ko cf. the errors :

> python convertSheet.py -i cno.rcs -o cno-fixed.rcs -c
Error: fail to read the input file
Traceback (most recent call last):
  File "convertSheet.py", line 265, in <module>
    main(sys.argv[1:])
  File "convertSheet.py", line 247, in main
    data = completeChange(data)
  File "convertSheet.py", line 169, in completeChange
    array = updateImage(data)
  File "convertSheet.py", line 42, in updateImage
    for p in data['background']:
TypeError: 'NoneType' object is not subscriptable

PS: i used python 3.7.4

I attached the sheet file (with characters) :
[cno.zip](https://github.com/Rolisteam/RCharacterSheet/files/3731393/cno.zip)

**Comment by obiwankennedy** [comment]
Yes, the first error message say it well: *Error: fail to read the input file*

I don't know what happened but as the input file was not read. It crashes in background image because it is the first step the script does. I should quit on error when this happen.

**Comment by sioc-de-narf** [comment]
Ok, so i tried :

- Minimal update => worked.

- Complete Update =>  didn't worked => white page 

- The Script : Ko cf. the errors :

> python convertSheet.py -i cno.rcs -o cno-fixed.rcs -c
Error: fail to read the input file
Traceback (most recent call last):
  File "convertSheet.py", line 265, in <module>
    main(sys.argv[1:])
  File "convertSheet.py", line 247, in main
    data = completeChange(data)
  File "convertSheet.py", line 169, in completeChange
    array = updateImage(data)
  File "convertSheet.py", line 42, in updateImage
    for p in data['background']:
TypeError: 'NoneType' object is not subscriptable

PS: i used python 3.7.4

I attached the sheet file (with characters) :
[cno.zip](https://github.com/Rolisteam/RCharacterSheet/files/3731393/cno.zip)

**Comment by sioc-de-narf** [comment]
the Minimal update that worked was on that file too ...

**Comment by obiwankennedy** [comment]
Yes, I can understand that, but perhaps you add some invisible character or something. Have you tried a second time ? on my side, the script worked fine. I did not yet checked the charactersheet but no error message.
